const IMPORT_TYPE_CONTAINER = 'container'
const IMPORT_TYPE_COMPONENT = 'component'
const IMPORT_TYPE_MIXIN = 'mixin'
const IMPORT_TYPE_REDUCER = 'reducer'
const IMPORT_TYPE_MODEL = 'model'
const IMPORT_TYPE_UTIL = 'util'
const IMPORT_TYPE_CONST = 'const'
const IMPORT_TYPE_OTHER = 'other'

const IMPORT_TYPES = [
  IMPORT_TYPE_CONTAINER,
  IMPORT_TYPE_COMPONENT,
  IMPORT_TYPE_MIXIN,
  IMPORT_TYPE_REDUCER,
  IMPORT_TYPE_MODEL,
  IMPORT_TYPE_UTIL,
  IMPORT_TYPE_CONST,
  IMPORT_TYPE_OTHER
]

const IMPORT_TYPE_MAP = IMPORT_TYPES.reduce((o, prop) => {
  o[prop] = true
  return o
}, {})

module.exports = {
  IMPORT_TYPE_CONTAINER,
  IMPORT_TYPE_COMPONENT,
  IMPORT_TYPE_MIXIN,
  IMPORT_TYPE_REDUCER,
  IMPORT_TYPE_MODEL,
  IMPORT_TYPE_UTIL,
  IMPORT_TYPE_CONST,
  IMPORT_TYPE_OTHER,
  IMPORT_TYPES,
  IMPORT_TYPE_MAP
}
