#!/usr/bin/env node

const argv = require('minimist')(process.argv.slice(2))
const fs = require('fs')
const glob = require('glob')
const path = require('path')
const util = require('util')
const { Parser } = require('acorn')
const compose = require('./compose')
const sortComponentProps = require('./sortComponentProps')
const sortImports = require('./sortImports')
const toLineRows = require('./toLineRows')

const neat = context => {

  const { content } = context
  const isVue = context.ext === '.vue'

  let beforeJs = ''
  let afterJs = ''
  let code = content

  if (isVue) {
    const startTag = '<script>'
    const endTag = '</script>'
    const scriptStart = content.indexOf(startTag) + startTag.length
    const scriptEnd = content.indexOf(endTag)
    context.content = content.slice(scriptStart, scriptEnd)
    beforeJs = content.slice(0, scriptStart)
    afterJs = content.slice(scriptEnd)
  }
  const resultContext = compose(
    toLineRows,
    sortImports,
    sortComponentProps
  )(context)

  const fileContent = beforeJs + resultContext.rows.map(row => row.line).join('') + afterJs
  fs.writeFileSync(context.filePath, fileContent, 'utf8')
}

const cwd = process.cwd()
const filePaths = argv._.map(pattern => {
  if (pattern.includes('*')) {
    return glob.sync(pattern)
      .map(p => path.resolve(cwd, p))
  }
  return path.resolve(cwd, pattern)
})
.flat()

filePaths.forEach(filePath => {
  const content = fs.readFileSync(filePath, 'utf8')
  const ext = path.extname(filePath)
  const parserContext = {
    filePath,
    ext,
    source: content,
    content,
    argv,
    parse: code => Parser.parse(code, {
      ecmaVersion: 2020,
      sourceType: 'module'
    }),
    rows: []
  }
  neat(parserContext)
})
